Module4 task3
htmlacademy-adaptive/51735-mishka-22 pull request #11
Opened 2021-04-29 21:48 UTC by TamaraLavrina

2021-05-03 21:50 UTC, wrgraff requested changes
Какие-то лишние файлы есть, при чем с названиями неудачными:
- `source/img/Group-1.png`
- `source/img/Group.png`

Этому файлу название бы сменить, а то он дважды свг:
- `source/img/search.svg.svg`

Надо бы еще и состояния файлов привести в соответствие, а то тут половина работы над страницей формы отменяется.

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  text-decoration-style: solid 1px;
`style` отвечает за то, какого вида будет линия. За толщину линии этот параметр не отвечает.
Да зачем тебе это все задавать? Подчеркивание по умолчанию 1 пиксель и `solid`

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  color: #46c1ae;
А что не через переменную?

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +  text-decoration-color: rgba(70, 193, 174, 0.1);
Тут тоже можно использовать переменную, при чем препроцессор позволяет это делать прямо внутри `rgba()`:
```
rgba($color-primary, 0.3);
```

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +  }
Лучше не писать так вперемешку.
Например, здесь можно написать так, чтобы сперва шли все медиа с размерами, а затем медиа с плотностью

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  background-color: inherit;
Зачем делать фон наследуемым?

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  left: calc(50% + 109px);
Позиционирование самой кнопки все же не должно меняться в зависимости от открытия/закрытия.
Получается, у меня кнопка ездить будет по горизонтали при изменении состояния меню.

Поставь сразу как здесь =)

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  color: #000000;
Почему не переменная?

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  max-width: 260px;
Такая реализация подойдет только если ты увеличиваешь кликабельную область затем псевдоэлементом.
И еще это значение нужно сбросить.

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +.page-header--gradient {
Получается, градиент и там и там, но разный.
Идея с модификатором правильная, а имя модификатора может быть и более удачным

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/product-item.scss
> +    margin-right: 0;
Ты скидываешь у последнего элемента, поэтому если я создам, например, 4-й элемент списка, то все пойдет криво, так как в первом ряду окажется последний элемент с отступом справа, а сбросится отступ у 4-го элемента, который первый во втором ряду.

Вообще, для таких вещей ведь грид намного удобнее, там вся сетка строится из одного места тремя правилами.
И к размеру элементов привязки нет, что гибче.
Почему ты выбираешь флекс?

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/product-item.scss
> +    grid-template-rows: min-content  1fr min-content;
Лишний пробел затесался

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/user-nav.scss
> +  text-decoration: none;
Вообще не очень хорошо, наверное, что 2 очень похожих части интерфейса являются разными элементами и приходится им одни и те же стили задавать

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/video.scss
> +}
Кажется, этот файл не подключен

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/user-nav.scss
> +  max-width: 260px;
Тут с шириной та же история, что и в основном меню

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/manufacture-process.scss
> +  border-bottom: 1px solid $color-lightgrey-250;
Рамка только снизу разве?

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/manufacture-process.scss
> +    flex-direction: column;
Не очень люблю, когда флекс меняется на грид (или наоборот). Редко сетка настолько специфически перестраивается, что становится удобен другой метод.

А тут вообще странно. Ведь ты делаешь направление флекса колоночным: а ведь именно так работает грид по умолчанию. Так почему не использовать сразу его?

2021-05-03 21:50 UTC, wrgraff commented on source/sass/blocks/manufacture-process.scss
> +    width: 586px;
А зачем элементу здесь ширина, да еще и фиксированная?
Если ты задаешь грид или флекс, то лучше через их сетку управлять размерами элементов. И тут есть такая возможность, более того заголовок будет вести себя по умолчанию довольно удобно: растянется на всю ширину.

Элементам сетки же по возможности размеры задавать не стоит. Например, в данном случаем мы получаем горизонтальную прокрутку на десктопе из-за этого заголовка:
![изображение](https://user-images.githubusercontent.com/37917037/116937886-928e9880-ac72-11eb-9449-0a3db7879e45.png)

2021-05-04 11:34 UTC, TamaraLavrina commented on source/sass/blocks/main-header.scss
> +  }
поправлю в 5 модуле. поняла, что фото одно и то же на разных ширинах (у меня 2 фотографии сейчас - для мобильной и с начиная с таблета)

2021-05-04 16:37 UTC, TamaraLavrina commented on source/sass/blocks/manufacture-process.scss
> +    width: 586px;
поправила, но карточкам и секциям же мы можем задавать ширину?

2021-05-04 16:59 UTC, TamaraLavrina commented on source/catalog.html
> +              <h3 class="product-item__title title" id="img_1">Зайчик-попрыгайчик</h3>
я узнала, что мне еще надо модалку сделать))

2021-05-04 17:02 UTC, TamaraLavrina commented on source/sass/blocks/main-nav.scss
> +  max-width: 260px;
да, так и планирую. скоро начну тебя мучать вопросами про псевдоэлементы,

2021-05-04 17:04 UTC, TamaraLavrina commented on source/sass/blocks/product-item.scss
> +    margin-right: 0;
![Screenshot_2021-05-04 HTML Academy Мишка](https://user-images.githubusercontent.com/75179900/117041588-b0f8a080-ad13-11eb-9fad-c2a6f6c30f25.png)

я флекс выбрала, чтобы выровнять контент внутри, как то мне показалось проще, а сейчас не очень получается прибить нижний блок

2021-05-04 21:53 UTC, wrgraff commented on source/sass/blocks/manufacture-process.scss
> +    width: 586px;
Да в принципе мы везде можем, только не везде это лучший способ.
Если у нас ширина ограничена, то конечно где-то ее задать придется. Чем выше — тем лучше. В секциях вполне себе нормально.

2021-05-04 21:54 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  max-width: 260px;
Хорошо =)

2021-05-04 21:55 UTC, wrgraff commented on source/sass/blocks/product-item.scss
> +    margin-right: 0;
Чтобы выровнять контент внутри, тебе нужно, чтобы именно карточка была флексом.
А список карточек вполне может быть и гридом при этом.

2021-05-04 21:56 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +  }
Но я же просто про порядок свойств, чтобы код аккуратнее был )

2021-05-04 21:56 UTC, wrgraff commented on source/catalog.html
> +              <h3 class="product-item__title title" id="img_1">Зайчик-попрыгайчик</h3>
Да, это тоже... А что, ее нет в разметке? )

2021-05-05 13:14 UTC, wrgraff requested changes
Ну, вроде как сейчас уже сетки норм вполне.

Нашел пару мелочей, кое-что точно надо поправить, но ничего сложного и большого нет.

2021-05-05 13:14 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +.page-header--grey-bar {
Ну такое, шило на мыло )
"Градиент" на "серый". Они оба и градиент и оттенками серого сделаны.
Суть разницы в чем? На главной есть картинка, на других нет. Надо привязаться к подтексту, что это главная или что это хэдер с картинкой.

2021-05-05 13:14 UTC, wrgraff commented on source/catalog.html
> +        <h1 class="page-main__title page-main__title--catalog">Каталог товаров</h1>
А ты знаешь почему тебе пришлось ставить модификатор? Ведь текст на этих страницах в заголовках не отличается как-то по особенному.
Если умещается один, должен и другой умещаться.

Надо обязательно докапываться до сути. Узнавать, в чем разница.
У тебя на одной странице есть `page-main__header`, а на другой нет.

2021-05-05 13:14 UTC, wrgraff commented on source/catalog.html
> +              </picture>
Ох, ну вот зачем вы все спешите, куда спешите...
У тебя сейчас внимание на сетках должно быть. Потом — на декоре. И только потом картинки идут.
Не спеши. Сетки — самое сложное и объемное, потом быстрее пойдет.

Ну раз сделала, то сделала.

2021-05-05 13:14 UTC, wrgraff commented on source/catalog.html
> +                  width="260" height="195" aria-labelledby="img_1">
Не используй `aria-labelledby` на картинке, это не замена для `alt`.
`aria-labelledby` больше используется для секций всяких или блоков, описание которым дает текст, находящийся не внутри них.
`alt` не только описывает картинку, он еще и заменяет собой текст на странице, если картинка не загрузилась. И это не просто лейбл, а описание картинки.

К тому же, у вас в критериях именно alt требуют.

2021-05-05 13:14 UTC, wrgraff commented on source/catalog.html
> +              <img src="img/button-play-video.png" alt="проиграть видео" width="101" height="77">
Вообще, иконка тут декоративная.
Хорошо бы ее в фон, а сюда — скрытый текст.

2021-05-05 13:14 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +  padding-right: 0;
Лучше поправь разметку, чтобы одинаковая была =)

2021-05-05 17:59 UTC, TamaraLavrina commented on source/sass/blocks/user-nav.scss
> +  max-width: 260px;
поправила, в 5 модуле

2021-05-05 18:13 UTC, TamaraLavrina commented on source/catalog.html
> +            <a class="product-item__blank" href="#">
ну вроде как они на одну и ту же страницу ведут, значит должны быть одинаковыми/похожими но при этом элементы то разные. но можно я просто удалю классы, потому что я же их вообще не стилизую.

2021-05-05 19:11 UTC, TamaraLavrina commented on source/catalog.html
> +                  width="260" height="195" aria-labelledby="img_1">
я поменяла, не спорю, но знаешь что интересно - вытащила это из навыка по верстке карточных элементов. Академия там приводит пример именно для изображений товаров, чей альт дублирует заголовок
![изображение](https://user-images.githubusercontent.com/75179900/117195650-33559300-adee-11eb-80c2-498560c8ed3b.png)

2021-05-05 19:16 UTC, TamaraLavrina commented on source/catalog.html
> +              </picture>
нервничаю что так долго делаю, с сетками сама быстрее не могу, вот лезу в другие вещи

2021-05-06 10:16 UTC, wrgraff commented on source/catalog.html
> +            <a class="product-item__blank" href="#">
БЭМ — это про визуальное оформление. Одним и тем же блоком/элементом могут быть разные теги, так же как и один и тот же тег разными блоками/элементами.

Здесь важно не то, куда ссылка ведет, а что она из себя представляет. Одна картинку содержит, другая — заголовок.

Если они тебе для стилизации не нужны, то можно и убрать. Но если понадобятся, то называть их нужно не по тому, куда они ведут, а по тому, как выглядят и что делают в плане расположения элементами.
Например, ссылка под картинку может стать `product-item__img-wrapper`. Или же вообще сама стать `product-item__img`, а картинку через нее ставить без классов.

2021-05-06 10:22 UTC, wrgraff commented on source/catalog.html
> +        <h1 class="page-main__title page-title">Каталог товаров</h1>
Что-то тут не то доделано. Ты создала отдельный блок. Но как это решает проблему?
По-моему, проблему это добавляет, ведь для блока `page-title` внешние отступы и размеры задавать уже нельзя.

А обертка `page-main__wrapper` так и осталась.
Зачем она есть на странице каталога, если на странице с формой ты без нее обходишься? Структура шапки то одинакова на страницах.

2021-05-06 10:22 UTC, wrgraff commented on source/catalog.html
> +                  width="260" height="195" aria-labelledby="img_1">
Заметь, альт там тоже есть при этом =)
Нужно оставлять пустой альт тогда.

2021-05-06 10:26 UTC, wrgraff commented on source/sass/blocks/manufacture-process.scss
>      display: grid;
Так а чего не убрала то, всего одну строчку убрать нужно )

2021-05-06 10:26 UTC, wrgraff requested changes
Надо разметку исправить все-таки, не может она быть разной в одинаковых по структуре блоках

2021-05-06 10:27 UTC, wrgraff commented on source/catalog.html
> +              </picture>
Сетки домучаем и будет дальше легче

2021-05-06 15:06 UTC, wrgraff approved these changes

2021-05-06 15:06 UTC, merged