Module5 task1
htmlacademy-adaptive/51735-mishka-22 pull request #12
Opened 2021-05-08 09:39 UTC by TamaraLavrina

2021-05-09 17:01 UTC, wrgraff requested changes
А зачем в репозитории файл `Tablet.jpg`? =)

2021-05-09 17:01 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    //я пониамю что такой отступ справа неправильно, но не знаю как иначе
Так у тебя тут флекс. Элементы сбрасываются, если не помещаются в одну строку. Но со словом "Контакты" они помещаются, конечно. И ты паддингом делаешь элемент таким, чтобы рядом не влезало ничего.
В принципе, логично =) Только зачем паддингом? Поставь ширину 100%, да и все.

2021-05-10 12:14 UTC, TamaraLavrina commented on source/icon.svg
> +</svg>
удалила

2021-05-10 13:32 UTC, TamaraLavrina commented on source/index.html
> +        <img class="map" src="img/map.jpg" width="768" height="457">
а нужно ли их ретинизировать?

2021-05-10 13:54 UTC, TamaraLavrina commented on source/sass/blocks/product-special.scss
> +  width: 100%;
![изображение](https://user-images.githubusercontent.com/75179900/117670144-4b436300-b1b0-11eb-9342-1b1e58d8b5da.png)

2021-05-10 20:40 UTC, TamaraLavrina commented on source/sass/blocks/main-nav.scss
> +  height: 100%;
не поняла - высоту/ширину просто удалить? ведь нельзя же прописать еще и right/bottom

2021-05-12 09:12 UTC, wrgraff commented on source/img/sprite.svg
> +  <symbol id="search" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
В принципе, твой спрайт работает.
Но почему-то везде проставлен `fill="none"`. Ну, конечно, в отсутствии заливки иконку будет не видно )
Нужно поставить параметр здесь, или же определять его через стили.

Есть и еще вариант, гораздо более удобный. Прописать туда `currentColor`. Это такое специальное ключевое слово, которое будет принимать текущий цвет. То есть, чтобы поменять заливку, тебе достаточно будет изменить цвет самой ссылке (или иконке: смотря что нужно) и параметр сам передастся в картинку.

2021-05-12 09:12 UTC, wrgraff commented on source/img/zigzag-line-desktop.svg.svg
> +<svg width="320" height="6" viewBox="0 0 320 6" fill="none" xmlns="http://www.w3.org/2000/svg">
Имя слоя в Фигме было с `.svg` на конце. Надо убирать его в таких случаях, а то странное имя файла выходит )

2021-05-12 09:12 UTC, wrgraff commented on source/index.html
> +        <img class="map" src="img/map.jpg" width="768" height="457">
Ну по идее хорошо бы.
С другой стороны, картинка по сути фолбек. Настолько ли то необходимо?
Ну и еще вопрос, хватает ли там у нее разрешения для ретины. Сдается мне, что нет, и картинка там изначально не ретиновая. Так что ретину мы из нее не сделаем.

2021-05-12 09:23 UTC, wrgraff commented on source/index.html
> +  <script src="mobile-menu__open.js"></script>
Не называй файлы по БЭМу, это странно )
И они могут использоваться очень по разному, совсем вне зависимости от контекста. Так что не стоит привязывать их к чему-либо.

2021-05-12 09:23 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  background-size: 21px 20px;
Смотри как это выглядит:
У тебя сама кнопка 50 на 50. Иконку надо поставить ы

2021-05-12 10:30 UTC, wrgraff requested changes
Отлично, много работы сделала и уже гораздо лучше стало.
Нужно еще доработать несколько моментов.

2021-05-12 10:30 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +      background-size: 52%;
Какие-то очень странные параметры.
Почему ширина 200%? Разве тебе нужно, чтобы она была больше, чем видимая область?
Почему размер фона такой странный? Он у тебя по ширине должен сам подстроиться, потому что повторяется по горизонтали. А по высоту лучше дать 100%. И менять высоту псевдоэлемента.

2021-05-12 10:30 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +      background-position: -5px 11px;
Когда смотрю на макет, мне не вот как-то кажется, что если фон поставить центр, то он отлично по макету встанет...
![изображение](https://user-images.githubusercontent.com/37917037/117957034-4dc5ca00-b322-11eb-89b1-e89ae3b074c0.png)

2021-05-12 10:30 UTC, wrgraff commented on source/sass/blocks/product-special.scss
> +    margin-bottom: 80px;
Это несколько неудобно и непредсказуемо. А что, если строк станет больше?

Ты подтягиваешь тянущийся контент под ПП некой такой распоркой снизу. Почти в прямом смысле костылем подпираешь =)
А это не очень хорошо, надо изменить поведение блоков на то, что тебе нужно. Ведь все будет намного проще, если элементы внутри этого блока растягиваться равномерно не будут?
Используй `align-content: start`.

2021-05-12 10:30 UTC, wrgraff commented on source/sass/blocks/main-header-menu.scss
> +  transition: margin-top 0s ease-in-out 0s;
А зачем тебе `transition` с нулевыми значениями?

2021-05-12 10:30 UTC, wrgraff commented on source/sass/blocks/main-header-menu.scss
> +  margin-top: -5px;
Лучше используй `transform` для смещения. Потому что отступ может на что-то повлиять (сейчас не влияет, но мало ли что и как в верстке может измениться).
`transform` будет только визуально смещать элемент, это будет надежнее.

2021-05-12 10:30 UTC, wrgraff commented on source/sass/global/variables.scss
> +$primary-color-350-hover:#59d5bc;
Такая цветовая система все-таки не предполагает, что есть оттенки исключительно для наведения.
Есть степень оттенка и дальше они уже используются так или иначе, может быть один и тот же в стилях для наведения или нажатия или еще где-то.

2021-05-12 10:34 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  height: 100%;
Почему нельзя? Можно.
Убираешь ширину и высоту и ставишь `right` и `left` вместе с `top` и `bottom` сразу. Тогда элемент привяжется одновременно всеми сторонами к родителю

2021-05-13 14:20 UTC, TamaraLavrina commented on source/sass/blocks/main-header.scss
> +      background-position: -5px 11px;
да, но центр волны у меня получается гребень.  и сама волна растянута на декстопе. пока оставила только планшетную версию, вдруг еще домучаю

2021-05-14 16:27 UTC, wrgraff approved these changes
Давай так. Я приму ПР, чтобы не тормозить тебя. Тут мелочи в общем совсем. Некоторые вообще не критичны.
Поправь их в следующем задании просто.

Чтобы волнистая линия на планшете стояла шире, чем контент, можно поставить ее левую и правую сторону на значения отрицательные, которые компенсируют размеры отступов.
Ширину убрать надо будет, конечно.
_Если ничего не понятно, пиши в телегу =)_

2021-05-14 16:27 UTC, wrgraff commented on source/sass/blocks/social.scss
> +  margin: 10px 10px;
Не надо отступы иконке ставить.
Выставь ее просто по центру. Сделать это довольно легко:
- делаешь из ссылки флекс
- задаешь флексу центрирование по вертикали и горизонтали
  либо ставишь иконке отступ `auto` (помнишь же как он во флексе работает?)

2021-05-14 16:27 UTC, wrgraff commented on source/sass/blocks/social.scss
> +  margin: 10px 10px;
У тебя должна получиться в итоге аккуратная сетка для соцсетей, с равными отступами со всех сторон. И растянуть даже если, должна попадать в макет

2021-05-14 16:27 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +}
Мудрено )
Можно сделать `modal` полупрозрачным перекрытием целиком, а внутри сделать `modal__container`, который будет уже с контентом.
Обычно делают так, это довольно гибко и удобно

2021-05-14 16:27 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +.modal::after {
А этот псевдо вообще что делает? Как-то удалил и не изменилось ничего

2021-05-14 16:27 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +      width: 100%;
Смотри, по умолчанию у тебя фон от левого края повторяется.
Слева направо.

Если ты задаешь положение фона по центру, то он будет от центра повторяться и налево и направо. А картинка встанет своим центром на центр блока.

Как видишь, она своим центром встанет как раз туда, куда надо:
![изображение](https://user-images.githubusercontent.com/37917037/118299741-cc209880-b4e9-11eb-8c9f-d583f0f596ea.png)

2021-05-14 16:27 UTC, wrgraff commented on source/sass/blocks/main-header-menu.scss
> +  transform: translate(0, -5px);
Можно `translateY` использовать, сдвигать только по вертикали элемент.
А еще нужно заранее предусмотреть размер элемента, чтобы он не вылезал полностью из-за "волны":
![изображение](https://user-images.githubusercontent.com/37917037/118300042-2de10280-b4ea-11eb-9109-0522e19ccc3c.png)

2021-05-14 16:27 UTC, merged