Module5 task2
htmlacademy-adaptive/51735-mishka-22 pull request #13
Opened 2021-05-15 21:59 UTC by TamaraLavrina

из индекса не переделала еще перекрытие модалки. Еще вроде как волна встала и даже попадает в центр, но при ширине более 1150 - очень странный ээфект (на самом деле поменяла волну - была планшетная, стала десктопная). По форме не понятно как быть с тремя  столбиками-чекбоксами. Ну и с legend.

2021-05-17 11:09 UTC, wrgraff requested changes

2021-05-17 11:09 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +      background-position: center;
Записал пояснительное видео на тему этой линии.
Небольшое, на 10 минут.
[Закинул на Ютуб](https://youtu.be/Zd6BBehIlYA), думаю, что как доберешься до домашки, оно там обработается уже

2021-05-17 11:16 UTC, wrgraff reviewed
Еще заметил, что на странице каталога в меню нет ссылки на страницу формы

2021-05-17 11:16 UTC, wrgraff commented on source/sass/blocks/form.scss
> +    top: 67px;
В принципе, через абсолют у тебя не должно быть проблем с расположением элемента `legend`.

Ты можешь немного разные стили написать для тех, что настоящие `legend` и для тех, что `span`. Потому что вторые хорошо могут встать в сетку там, где контактные данные. А первые придется абсолюом все равно переставлять

2021-05-17 18:22 UTC, TamaraLavrina commented on source/sass/blocks/text-field.scss
> +  position: absolute;
вроде как поправила

> 
> 
> Еще заметил, что на странице каталога в меню нет ссылки на страницу формы

в следующе ветке поправлено (module5-task3)

2021-05-17 18:26 UTC, TamaraLavrina commented on source/sass/blocks/main-header.scss
> +      background-position: center;
смотри, а вот линия которая настоящий зигзаг - она же тоже не должна быть размером 100%, вот ей я задаю -30 влево/вправо и ее высоту как в фигме.  также ставлю ширину auto? вроде смотрится хорошо, но в пиксель не попадаю.

2021-05-18 10:16 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +      background-position: center;
А отрицательное значение — оно для десктопа уже не нужно.
Что касается линий, но они у тебя все как-то не очень ровно попадают. Но с масштабами и размерами все правильно. Возможно, они экспортированы как-то не слишком удачно.
Давай отложим этот вопрос до ПП: если что, я помогу с подгонкой в формате консультации и с экспортом разберемся заодно, посмотрим как ты это делаешь.

2021-05-18 10:18 UTC, wrgraff approved these changes

2021-05-18 10:18 UTC, wrgraff commented on source/sass/blocks/chooser.scss
> +    margin-bottom: 25px;
Тут конечно не отступом у списка надо было компенсировать, а у `form__group` изменить внутренние.
Но это уже мелочи

2021-05-18 10:19 UTC, merged