стилизация index
htmlacademy-adaptive/51735-mishka-22 pull request #6
Opened 2021-04-05 09:46 UTC by TamaraLavrina

2021-04-05 11:51 UTC, babtshe requested changes

2021-04-05 11:51 UTC, babtshe commented on source/index.html
> +          <label">
❗

2021-04-05 11:51 UTC, babtshe commented on source/index.html
> +            <input class="user-nav__search" type="search" name="search" placeholder="Поиск по сайту">
инпут неплохо бы в форму обернуть

2021-04-05 11:51 UTC, babtshe commented on source/index.html
> +          <button type="button" class="slider__toggle slider__toggle--next"></button>
Если существует всего два вида кнопок, то зачем тогда второй модификатор? Немодифицированное состояние тоже учитывается ведь.

2021-04-05 11:51 UTC, babtshe commented on source/index.html
> +        <a href="#" class="reviews__write-us button" href="form.html">Написать</a>
многовато `href`

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/about.scss
> +.about-title {
каждый блок должен быть в отдельном файле. Так что здесь либо опечатка, либо кандидат на переезд.

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/footer.scss
> +.page-footer {
название файла должно соответствовать названию блока. В данном случае стоит либо поменять названия, либо вынести в отдельные файлы.

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/footer.scss
> +  @include side-margin;
стоит аккуратно использовать `@include`. Вспомнишь ли ты через полгода, что означает `side-margin` не заглядывая в исходный код? В таких случаях очень важно придумывать понятные названия переменных. В данном случае правки на твоё усмотрение.

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/logo.scss
> +.logo-image {
❗

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/logo.scss
> +  height: 35px;
лучше не использовать фиксированную высоту без необходимости. Если картинка окажется больше, то она будет выпадать из блока.

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/main-header.scss
> +  &__layout {
так тоже можно, но по правилам этого интенсива нельзя. См [критерий](https://up.htmlacademy.ru/adaptive/22/criteries#d11)

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/main-header.scss
> +.main-header h1 {
тут лучше класс присвоить заголовку.

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/main-nav.scss
> +  a {
❗

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/main-product-special.scss
> +.main-product-special__product {
стоит подумать над названием.

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/main-product-special.scss
> +.product__description {
❗

2021-04-05 11:51 UTC, babtshe commented on source/sass/blocks/page__header.scss
> +.page__header .logo {
лучше не увеличивать специфичность селекторов без явной необходимости

2021-04-05 11:51 UTC, babtshe commented on source/sass/global/fonts.scss
> +    url("/fonts/opensans.woff2") format(woff2),
Обрати внимание на пути: 
![image](https://user-images.githubusercontent.com/30229773/113570853-de233780-961d-11eb-94eb-bee7897d89ff.png)

2021-04-06 07:11 UTC, babtshe requested changes

2021-04-06 07:11 UTC, babtshe commented on source/index.html
> +
Для чего нужен класс `header-wrapper` на этих элементах?

2021-04-06 07:11 UTC, babtshe commented on source/index.html
> +          <form action="https://echo.htmlacademy.ru/courses" method="post">
Почему здесь именно POST используется?

2021-04-06 07:11 UTC, babtshe commented on source/sass/blocks/about.scss
> +    background-image: url("../../img/icon-flower.svg");
Проблемы с путями остались: 
![image](https://user-images.githubusercontent.com/30229773/113671875-9d7bfa80-96bf-11eb-8ab7-27d59ca2acad.png)

2021-04-06 07:11 UTC, babtshe commented on source/sass/blocks/header-wrapper.scss
> +.header-wrapper .toggle {
см https://ru.bem.info/methodology/css/#%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B

2021-04-06 07:11 UTC, babtshe commented on source/sass/blocks/main-nav.scss
> +.main-nav__item a {
см https://ru.bem.info/methodology/css/#%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B

2021-04-06 07:11 UTC, babtshe commented on source/sass/global/fonts.scss
> +    url("../../fonts/opensansbold.woff2") format("woff2"),
есть смысл разобраться как работают абсолютные и относительные ссылки. Если что-то работает локально это не гарантирует работу на сервере: https://htmlacademy-adaptive.github.io/51735-mishka-22/6/

2021-04-06 07:40 UTC, TamaraLavrina commented on source/index.html
> +
"Уши" будут во внешнем блоке, а wrapper - центрирует. Что не так?

2021-04-06 07:44 UTC, TamaraLavrina commented on source/index.html
> +          <form action="https://echo.htmlacademy.ru/courses" method="post">
Запрос GET передает данные  в виде пар "имя-значение", а запрос POST передает данные в теле запроса . Насколько я понимаю get будет хорошо в фильтре товаров, а в пользовательских запросах формах обратной связи и логинах - post

2021-04-06 17:52 UTC, wrgraff reviewed
Вот, я много тебе понаписал, но это не страшно: другой взгляд с новой стороны, поэтому так.

В целом все хорошо.
Самые критичные моменты я пометил иконкой с ракетой. Остальное очень хотелось бы поправить, но это не настолько критично.

2021-04-06 17:52 UTC, wrgraff commented on source/index.html
> +          <button type="button" class="slider__toggle slider__toggle"></button>
Модификатор видимо убрала (я бы оставил, кстати, так деклоративнее код выглядит) и осталось 2 одинаковых класса.
И текст внутри пропал. Надо или скрытым было его сделать, или `aria-label` тогда повесить.

2021-04-06 17:52 UTC, wrgraff commented on source/index.html
> +      <a class="contacts_button button" href="#">Напишите нам</a>
Одно подчеркивание потерялось

2021-04-06 17:52 UTC, wrgraff commented on source/sass/global/variables.scss
> +$mobile-width-only: 767px;
Вьюпорт это скорее диапазон. А тут точки перестроения, они скорее брейкпоинты

2021-04-06 17:52 UTC, wrgraff commented on source/sass/global/variables.scss
> +$head-text:#000000;
Ох, запутаешься ты в этих цветах в итоге...
Я для себя взял вот такую систему именования цветов:
<img width="369" alt="изображение" src="https://user-images.githubusercontent.com/37917037/113751059-30df1b00-9714-11eb-97ed-5aeeba0873f1.png">

Эта система давно применяется в [Google Material](https://material.io/design/color/the-color-system.html#tools-for-picking-colors). Цифра означает "вес" цвета (по ссылке там чуть ниже есть табличка "2014 Material Design color palettes", там хорошо понятно что к чему).
Так ориентироваться  сильно проще между оттенками.

И еще да, я не пренебрегаю иногда назвать цвет именем цвета (хотя вместе с тем использую и абстрактные имена primary / secondary). Делаю я так, потому что за несколько лет работы мне еще ни разу не доводилось кардинально менять цвет с синего на зеленый, чтобы он прям переменно не соответствовал больше.
Не представляю, что должно случиться с проектом, чтобы его палитра серого стала вдруг фиолетовой =)

2021-04-06 17:52 UTC, wrgraff commented on source/sass/global/variables.scss
> +}
Миксин ради одного правила это перебор.
Ведь намного понятнее, когда в коде написано `border-top: 1px solid $border-color;`, чем `@include border;`.
При этом ничего особо и не выигрываем по чистоте кода.

2021-04-06 17:52 UTC, wrgraff commented on source/sass/global/variables.scss
> +}
Вот тем более с неймингом пока руку не набила, лучше сдерживаться от создания лишних миксинов.
Запутаться очень легко: `border` это верхняя рамка, а `border-b` нижняя. А почему не `border-t`? А еще сокращение одной буквой не лучший способ ведь увеличить читаемость.

Да и вообще большое количество миксинов скорее усложняет ориентирование в проекте.
Я раньше много их делал, а теперь вот у меня на сайт в котором 71 БЭМ-блок приходится 3 миксина всего.

2021-04-06 17:52 UTC, wrgraff commented on source/sass/global/variables.scss
> +}
Ну тут менее критично, хотя надо сказать, заголовков там таких 2 или 3 на весь сайт )

2021-04-06 17:52 UTC, wrgraff commented on source/sass/global/fonts.scss
> +    url("../fonts/opensansbold.woff") format("woff");
Зато порядок и форматирование правильные =)

2021-04-07 19:11 UTC, wrgraff reviewed
Ну вот, уже все причесано почти )

2021-04-07 19:11 UTC, wrgraff commented on source/catalog.html
> +          <li class="product-catalog__product-item">
Блок `product-list` у тебя и правда кажется не использовался, а вот `product-item` еще нужен, элементы у него есть

2021-04-07 19:11 UTC, wrgraff commented on source/catalog.html
> +              <a class="buy__add-cart" aria-label="Добавить в корзину" href="#">
А где блок `buy`?
Я думаю, тут небольшая невнимательность имеет место =)
Попробуй попроверять себя после изменений классов [инструментом от Йоксель](https://yoksel.github.io/html-tree/). Он там немного глючить может на теге html, но в остальном подсвечивает все правильно.

2021-04-07 19:11 UTC, wrgraff commented on source/catalog.html
> +        </ul>
Интересно, а зачем тебе можификаторы, если внутри есть картинки?

2021-04-07 19:11 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +    background-position: 50% 50%;
А если вынести эти 2 параметра в класс `.reviews__toggle`, то не придется писать их 2 раза

2021-04-07 19:57 UTC, merged